# Generated by Django 5.2.14 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('programa', models.CharField(choices=[('PGEDA', 'PGEDA'), ('PPEB', 'PPEB')], max_length=10)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoAprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_access', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDING', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('inscricao', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('issuing_body', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('voter_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_section', models.CharField(blank=True, max_length=10, null=True)),
                ('military_id', models.CharField(blank=True, max_length=50, null=True)),
                ('military_series', models.CharField(blank=True, max_length=10, null=True)),
                ('military_category', models.CharField(blank=True, max_length=50, null=True)),
                ('military_dispatch_date', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('race_color', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_state', models.CharField(blank=True, max_length=2, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('emergency_contact_1', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone_1', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_2', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True)),
                ('lattes_url', models.URLField(blank=True, null=True)),
                ('research_area', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('compe_code', models.CharField(blank=True, max_length=10, null=True)),
                ('agency', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('program_level', models.CharField(blank=True, max_length=10, null=True)),
                ('formulario_enviado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidato_aprovado', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.periodomatricula')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='enrollments.candidatoaprovado')),
            ],
        ),
    ]
