# Generated by Django 4.2.13 on 2026-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('date_of_birth', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('issuing_body', models.CharField(max_length=50, verbose_name='Órgão Expedidor')),
                ('dispatch_date', models.DateField(blank=True, null=True, verbose_name='Data de Expedição RG')),
                ('voter_id', models.CharField(max_length=20, verbose_name='Título de Eleitor')),
                ('voter_zone', models.CharField(max_length=10, verbose_name='Zona')),
                ('voter_section', models.CharField(max_length=10, verbose_name='Seção')),
                ('military_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificado Militar')),
                ('military_date', models.DateField(blank=True, null=True, verbose_name='Data Exp. Militar')),
                ('military_series', models.CharField(blank=True, max_length=10, null=True)),
                ('military_category', models.CharField(blank=True, max_length=50, null=True)),
                ('military_dispatch_date', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('father_name', models.CharField(max_length=255, verbose_name='Nome do Pai')),
                ('gender', models.CharField(max_length=20, verbose_name='Sexo')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Estado Civil')),
                ('race_color', models.CharField(max_length=20, verbose_name='Raça/Cor')),
                ('birth_country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('birth_state', models.CharField(max_length=2, verbose_name='UF de Nascimento')),
                ('birth_city', models.CharField(max_length=100, verbose_name='Município de Nascimento')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Celular')),
                ('zip_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('emergency_contact_1', models.CharField(max_length=255, verbose_name='Contato Próximo 1')),
                ('emergency_phone_1', models.CharField(max_length=20, verbose_name='Celular Contato 1')),
                ('emergency_contact_2', models.CharField(max_length=255, verbose_name='Contato Próximo 2')),
                ('emergency_phone_2', models.CharField(max_length=20, verbose_name='Celular Contato 2')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('course', models.CharField(max_length=255, verbose_name='Curso')),
                ('graduation_year', models.CharField(max_length=4, verbose_name='Ano de Conclusão')),
                ('bank_name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
    ]
