# Generated by Django 5.2.14 on 2026-05-30 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('social_name', models.CharField(blank=True, max_length=255, null=True)),
                ('program_level', models.CharField(choices=[('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=10)),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('date_of_birth', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('issuing_body', models.CharField(max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('voter_id', models.CharField(max_length=20)),
                ('voter_zone', models.CharField(max_length=10)),
                ('voter_section', models.CharField(max_length=10)),
                ('military_id', models.CharField(blank=True, max_length=50, null=True)),
                ('military_date', models.DateField(blank=True, null=True)),
                ('military_series', models.CharField(blank=True, max_length=10, null=True)),
                ('military_category', models.CharField(blank=True, max_length=50, null=True)),
                ('military_dispatch_date', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=50)),
                ('race_color', models.CharField(max_length=20)),
                ('birth_country', models.CharField(default='Brasil', max_length=100)),
                ('birth_state', models.CharField(max_length=2)),
                ('birth_city', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('emergency_contact_1', models.CharField(max_length=255)),
                ('emergency_phone_1', models.CharField(max_length=20)),
                ('emergency_contact_2', models.CharField(max_length=255)),
                ('emergency_phone_2', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=4)),
                ('bank_name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('programa', models.CharField(choices=[('PGEDA', 'PGEDA'), ('PPEB', 'PPEB')], max_length=10)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(choices=[('PGEDA', 'PGEDA'), ('PPEB', 'PPEB')], default='PGEDA', max_length=10)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('is_first_access', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado no Processo'), ('PRE_MATRICULA', 'Pré-Matrícula Iniciada'), ('CONCLUIDA', 'Matrícula Concluída')], default='APROVADO', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoAprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('inscricao', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('is_first_access', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidato_aprovado', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.periodomatricula')),
            ],
        ),
    ]
