# Generated by Django 5.2.14 on 2026-05-23 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('is_first_access', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado no Processo'), ('PRE_MATRICULA', 'Pré-Matrícula Iniciada'), ('CONCLUIDA', 'Matrícula Concluída')], default='APROVADO', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
