# Generated by Django 5.2.14 on 2026-05-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
