# Generated by Django 5.2.14 on 2026-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollment_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='programa',
            field=models.CharField(choices=[('PGEDA', 'PGEDA'), ('PPEB', 'PPEB')], default='PGEDA', max_length=10),
        ),
    ]
