# Generated by Django 5.2.14 on 2026-06-26 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_candidatos_por_periodo', models.IntegerField(default=100)),
                ('aceitar_novas_inscricoes', models.BooleanField(default=True)),
                ('email_template_aprovado', models.TextField(default='Parabéns! Sua pré-matrícula foi aprovada.')),
                ('email_template_aguardando', models.TextField(default='Sua inscrição está em análise. Aguarde o retorno.')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10)),
                ('candidatos_por_pagina', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Parâmetros do Sistema',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('avaliador', 'Avaliador')], default='avaliador', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
